### ISSUE TITLE
Memory allocation problem

### ISSUE THREAD

**Issue by DAKYSKYE** [Southclaws/samp-logger#2]
Calling functions in each other causes ***Stack/heap collision***
That logger has likewise problem -> if **_s**, **_i**, **_f** are called several times inside **log()**, ***Run time error 3: "Stack/heap collision (insufficient stack size)"*** comes up.

**Comment by Southclaws** [comment]
This is caused by the `LOGGER_FIELD` functions allocating `MAX_FIELD_NAME + 3 + MAX_FIELD_VALUE` cells, which amounts to 275 cells total. Calling this `MAX_EVENT_FIELDS` times in a call results in a total allocation of 2200 cells being allocated on the stack not including those allocated in `log` (and others) which is `MAX_EVENT_LENGTH` which results in an allocation of over 8000 cells.

A quick solution for this would be to use a heap-allocated array for all `_` helpers, as long as this is `static` and all functions properly zero the array before using it, it will be fine to use this method instead of stack memory in this case.
